version: '3.3'
services:
  db:
     image: mysql:8.0
     container_name: "fortify-ssc-db"
     volumes:
       - /containervolume/fortify-ssc/mysql/data:/var/lib/mysql
       - /containervolume/fortify-ssc/mysql/dump:/docker-entrypoint-initdb.d
       - /containervolume/fortify-ssc/mysql/my.cnf:/etc/mysql/my.cnf
     environment:
       MYSQL_ROOT_PASSWORD: P@ssw0rd
       MYSQL_DATABASE: ssc
       MYSQL_USER: sscadmin
       MYSQL_PASSWORD: P@ssw0rd

  web:
    depends_on:
      - db
    image: tomcat
    container_name: "fortify-ssc"
    volumes:
      - /containervolume/fortify-ssc/webapps/ssc.war:/usr/local/tomcat/webapps/ssc.war
    expose:
      - '8080'
      - '8009'
    environment:
       MYSQL_ROOT_PASSWORD: P@ssw0rd
       MYSQL_DATABASE: ssc
       MYSQL_USER: sscadmin
       MYSQL_PASSWORD: P@ssw0rd

networks:
  default:
    external:
       name: infranet

